# Generated by Django 3.0.8 on 2022-06-12 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_the_class', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LessonPlanName', models.CharField(blank=True, max_length=200)),
                ('semester', models.CharField(max_length=200)),
                ('clas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lb.Class')),
                ('faculty_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subject_A_SubjectCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LogBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_of_the_paper', models.CharField(max_length=200)),
                ('semester', models.CharField(max_length=200)),
                ('clas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lb.Class')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lb.Department')),
                ('faculty_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lb.Subject_A_SubjectCode')),
            ],
        ),
        migrations.CreateModel(
            name='LessonPlanExtended',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecturenumber_and_hour', models.IntegerField(default=1)),
                ('Date_planned', models.DateField()),
                ('topics_to_be_covered', models.TextField(max_length=200)),
                ('Actual_date', models.DateField()),
                ('Remarks', models.CharField(max_length=200)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lb.LessonPlan')),
            ],
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='related_with',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lb.LogBook'),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='sub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lb.Subject_A_SubjectCode'),
        ),
        migrations.CreateModel(
            name='CourseObj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectives', models.TextField(blank=True, max_length=400)),
                ('outcomes', models.TextField(blank=True, max_length=400)),
                ('inference', models.TextField(blank=True, max_length=400)),
                ('related_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lb.LogBook')),
            ],
        ),
    ]
