# Generated by Django 3.0.8 on 2022-06-12 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lb', '0002_lessonplanextended_related_with'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonplan',
            name='clas',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='lb.Class'),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='related_with',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='lb.LogBook'),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='semester',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='sub',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='lb.Subject_A_SubjectCode'),
        ),
    ]
