# Generated by Django 3.0.8 on 2022-06-12 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lb', '0004_cia_1_result_analysis_cia_2_result_analysis_correctiveandpreventivecia_1_correctiveandpreventivecia_'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cia_1_result_analysis',
            name='date_of_examination',
            field=models.CharField(blank=True, default='dd/mm/yyyy', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cia_1_result_analysis',
            name='name_of_the_examination',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cia_1_result_analysis',
            name='no_of_students_appeared',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='cia_1_result_analysis',
            name='no_of_students_below_40',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='cia_1_result_analysis',
            name='no_of_students_below_40_60',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='cia_1_result_analysis',
            name='no_of_students_below_60_75',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='cia_1_result_analysis',
            name='no_of_students_below_75_100',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='cia_1_result_analysis',
            name='no_of_students_passed',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='cia_1_result_analysis',
            name='no_pf_students_failed',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='cia_1_result_analysis',
            name='percentage_of_pass',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cia_1_result_analysis',
            name='total_number_of_students',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='cia_2_result_analysis',
            name='date_of_examination',
            field=models.CharField(blank=True, default='dd/mm/yyyy', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cia_2_result_analysis',
            name='name_of_the_examination',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cia_2_result_analysis',
            name='no_of_students_appeared',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='cia_2_result_analysis',
            name='no_of_students_below_40',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='cia_2_result_analysis',
            name='no_of_students_below_40_60',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='cia_2_result_analysis',
            name='no_of_students_below_60_75',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='cia_2_result_analysis',
            name='no_of_students_below_75_100',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='cia_2_result_analysis',
            name='no_of_students_passed',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='cia_2_result_analysis',
            name='no_pf_students_failed',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='cia_2_result_analysis',
            name='percentage_of_pass',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cia_2_result_analysis',
            name='total_number_of_students',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='correctiveandpreventivecia_1',
            name='coaching_detials',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='correctiveandpreventivecia_1',
            name='coaching_detials_for_advance_learners',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='correctiveandpreventivecia_1',
            name='corrective_action',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='correctiveandpreventivecia_1',
            name='exam_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lb.Cia_1_Result_Analysis'),
        ),
        migrations.AlterField(
            model_name='correctiveandpreventivecia_1',
            name='reason_for_failure',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='correctiveandpreventivecia_2',
            name='coaching_detials',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='correctiveandpreventivecia_2',
            name='coaching_detials_for_advance_learners',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='correctiveandpreventivecia_2',
            name='corrective_action',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='correctiveandpreventivecia_2',
            name='exam_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lb.Cia_1_Result_Analysis'),
        ),
        migrations.AlterField(
            model_name='correctiveandpreventivecia_2',
            name='reason_for_failure',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='correctiveandpreventivemodel',
            name='coaching_detials',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='correctiveandpreventivemodel',
            name='coaching_detials_for_advance_learners',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='correctiveandpreventivemodel',
            name='corrective_action',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='correctiveandpreventivemodel',
            name='exam_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lb.Cia_1_Result_Analysis'),
        ),
        migrations.AlterField(
            model_name='correctiveandpreventivemodel',
            name='reason_for_failure',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='correctiveandpreventiveuniversity',
            name='coaching_detials',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='correctiveandpreventiveuniversity',
            name='coaching_detials_for_advance_learners',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='correctiveandpreventiveuniversity',
            name='corrective_action',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='correctiveandpreventiveuniversity',
            name='exam_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lb.Cia_1_Result_Analysis'),
        ),
        migrations.AlterField(
            model_name='correctiveandpreventiveuniversity',
            name='reason_for_failure',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='model_result_analysis',
            name='date_of_examination',
            field=models.CharField(blank=True, default='dd/mm/yyyy', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='model_result_analysis',
            name='name_of_the_examination',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='model_result_analysis',
            name='no_of_students_appeared',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='model_result_analysis',
            name='no_of_students_below_40',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='model_result_analysis',
            name='no_of_students_below_40_60',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='model_result_analysis',
            name='no_of_students_below_60_75',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='model_result_analysis',
            name='no_of_students_below_75_100',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='model_result_analysis',
            name='no_of_students_passed',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='model_result_analysis',
            name='no_pf_students_failed',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='model_result_analysis',
            name='percentage_of_pass',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='model_result_analysis',
            name='total_number_of_students',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='remedialforcia_1',
            name='date',
            field=models.CharField(default='dd/mm/yyyy', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='remedialforcia_1',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='remedialforcia_1',
            name='reg_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='remedialforcia_1',
            name='s_no',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='remedialforcia_2',
            name='date',
            field=models.CharField(default='dd/mm/yyyy', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='remedialforcia_2',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='remedialforcia_2',
            name='reg_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='remedialforcia_2',
            name='related_with',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lb.LogBook'),
        ),
        migrations.AlterField(
            model_name='remedialforcia_2',
            name='s_no',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='remedialformodel',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='remedialformodel',
            name='reg_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='remedialformodel',
            name='related_with',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lb.LogBook'),
        ),
        migrations.AlterField(
            model_name='remedialformodel',
            name='s_no',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='remedialforuniversity',
            name='date',
            field=models.CharField(default='dd/mm/yyyy', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='remedialforuniversity',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='remedialforuniversity',
            name='reg_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='remedialforuniversity',
            name='s_no',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='university_result_analysis',
            name='date_of_examination',
            field=models.CharField(blank=True, default='dd/mm/yyyy', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='university_result_analysis',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lb.Department'),
        ),
        migrations.AlterField(
            model_name='university_result_analysis',
            name='faculty_handled',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='university_result_analysis',
            name='higher_mark',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='university_result_analysis',
            name='name_of_the_examination',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='university_result_analysis',
            name='no_of_students_appeared',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='university_result_analysis',
            name='no_of_students_below_40',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='university_result_analysis',
            name='no_of_students_below_40_60',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='university_result_analysis',
            name='no_of_students_below_60_75',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='university_result_analysis',
            name='no_of_students_below_75_100',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='university_result_analysis',
            name='no_of_students_passed',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='university_result_analysis',
            name='no_pf_students_failed',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='university_result_analysis',
            name='percentage_of_fail',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='university_result_analysis',
            name='percentage_of_pass',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='university_result_analysis',
            name='related_with',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lb.LogBook'),
        ),
        migrations.AlterField(
            model_name='university_result_analysis',
            name='year',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
