# Generated by Django 3.0.8 on 2022-06-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lb', '0005_auto_20220612_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentparticulars',
            name='retest_for_cia',
        ),
        migrations.AddField(
            model_name='studentparticulars',
            name='retest_for_cia1',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='studentparticulars',
            name='retest_for_cia2',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
