# Generated by Django 3.0.8 on 2022-05-31 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_Image', models.ImageField(upload_to='student-imgs/')),
                ('Student_Enrollment_Number', models.CharField(max_length=15)),
                ('Roll_Number', models.CharField(max_length=15)),
                ('University_Register_Number', models.CharField(max_length=200)),
                ('Name_Of_The_Student', models.CharField(max_length=200)),
                ('Father_Name', models.CharField(max_length=200)),
                ('Mother_Name', models.CharField(max_length=200)),
                ('Father_Occupation', models.CharField(max_length=200)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('Date_Of_Birth', models.DateField()),
                ('Differently_Abled_Person', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=4)),
                ('Visually_Challenged', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=4)),
                ('Marital_Status', models.CharField(default='Single', max_length=200)),
                ('Mother_Tongue', models.CharField(max_length=200)),
                ('Nationality', models.CharField(default='INDIAN', max_length=200)),
                ('Religion', models.CharField(max_length=200)),
                ('Aadhar_Number', models.CharField(max_length=12)),
                ('Address_For_Commumication', models.TextField(help_text='Enter a proper address', max_length=400, verbose_name='CommunicationAddress')),
                ('Mobile_Number', models.CharField(max_length=10)),
                ('Email_Address', models.EmailField(max_length=254)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
