# Generated by Django 3.0.8 on 2022-06-01 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Application_Number', models.CharField(blank=True, max_length=200)),
                ('Register_Number', models.CharField(blank=True, max_length=200)),
                ('Name', models.CharField(blank=True, max_length=200)),
                ('Parent_Mobile', models.CharField(blank=True, max_length=10)),
                ('Class', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='attendance.StudentDept')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Present_or_Absent', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], default=None, max_length=8)),
                ('Informed_or_not', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=None, max_length=3)),
                ('Date', models.DateField(null=True)),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Student')),
            ],
        ),
    ]
