# Generated by Django 3.0.8 on 2022-06-01 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendance_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.StudentDept'),
        ),
    ]
