# Generated by Django 3.0.8 on 2022-06-01 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_auto_20220601_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='Informed_or_not',
        ),
        migrations.DeleteModel(
            name='DailyReport',
        ),
    ]
