# Generated by Django 3.0.8 on 2022-06-01 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_auto_20220601_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalPresent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_Present', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Attendance')),
            ],
        ),
    ]
