# Generated by Django 3.0.8 on 2022-06-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_totalpresent'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='monthly_present',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='TotalPresent',
        ),
    ]
