# Generated by Django 3.0.8 on 2022-06-11 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_auto_20220611_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='monthly_present',
        ),
        migrations.AddField(
            model_name='attendance',
            name='monthly_present',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
