# Generated by Django 3.0.8 on 2022-05-31 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Staff_Image', models.ImageField(upload_to='staff-imgs/')),
                ('Name_Of_The_Staff', models.CharField(max_length=200)),
                ('Designation', models.CharField(max_length=200)),
                ('Qualification', models.CharField(max_length=200)),
                ('Date_Of_Appointment', models.DateField()),
                ('Experience', models.TextField(max_length=500)),
                ('SET_or_NET_Qualified', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=4)),
                ('Additional_Responsibility', models.TextField(max_length=300)),
                ('Date_Of_Birth', models.DateField()),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('Nationality', models.CharField(max_length=200)),
                ('Caste', models.CharField(max_length=200)),
                ('Address_Of_Communication', models.TextField(help_text='Enter a proper address', max_length=500, verbose_name='Communication Address')),
                ('Email_Id', models.EmailField(max_length=254)),
                ('Pan_Card_No', models.CharField(max_length=11)),
                ('Area_Of_Specialization', models.CharField(max_length=200)),
                ('Candidates_Produced_Mphil_or_Phd', models.CharField(blank=True, max_length=200, verbose_name='M.Phil/Ph.D, Candidates Produced')),
                ('Awards_or_Honours_Received', models.TextField(blank=True, max_length=400, verbose_name='Awards & Honours Received')),
                ('Papers_Published', models.TextField(blank=True, max_length=500, verbose_name='Papers Published in Journals (N/I)')),
                ('Papers_Presented', models.TextField(blank=True, max_length=400, verbose_name='Papers Presented in Conferences')),
                ('Workshops_Attended', models.TextField(blank=True, max_length=500)),
                ('Con_or_semi', models.TextField(blank=True, max_length=500, verbose_name='Conference/Seminar Attended')),
                ('Invited_Speaker', models.TextField(blank=True, max_length=500)),
                ('Programs_Organized', models.TextField(max_length=600, verbose_name='Programs organized (Conf/Workshop/FDP/GL/Webinar)...')),
                ('University_Rank_Produced', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
